project:
  type: website

website:
  title: "Vipul Cariappa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: /blogs/
        text: Blog
      - href: /projects/
        text: Projects
  favicon: /assets/images/favicon.ico
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
